chore: use curl instead of wget

diff --git a/install b/install
--- a/install
+++ b/install
@@ -1,7 +1,7 @@
 #!/bin/bash
 
 # OS:
-#   RedHat 7.9.2009(Core 3.10.0-1160.45.1.el7.x86_64 x86_64) 
+#   RedHat 7.9.2009(Core 3.10.0-1160.45.1.el7.x86_64 x86_64)
 #   CentOS 7
 #
 # Reference:
@@ -23,10 +23,10 @@ build_from_source() {
 
   log::info "[gcc::build_from_source] started ..."
 
-   which bzip2 >> /dev/null 2>&1
-   if [ "$?" != "0" ]; then
-     pm install -y bzip2
-   fi
+  which bzip2 >>/dev/null 2>&1
+  if [ "$?" != "0" ]; then
+    pm install -y bzip2
+  fi
 
   local build_dir=$(os::tmp)/build/zmicro_package_gcc
   mkdir -p $build_dir
@@ -52,7 +52,9 @@ build_from_source() {
 
   log::info "[gcc::build_from_source] download gcc $version source ..."
   log::info "[gcc::build_from_source] url: $url"
-  wget -c $url -O $filepath
+  # wget -c $url -O $filepath
+  os::download $filepath $url
+
   tar -xzf $filepath -C $build_dir
 
   mv $src_dir_tmp $src_dir
@@ -68,7 +70,7 @@ build_from_source() {
   ../configure --prefix=/usr/local/gcc --enable-languages=c,c++ --disable-multilib
 
   log::info "[gcc::build_from_source] build ..."
-  # make -j$(nproc) 
+  # make -j$(nproc)
   make
 
   log::info "[gcc::build_from_source] install ..."
@@ -107,7 +109,7 @@ core() {
     help
     exit 0
   fi
-  
+
   # only works when is build from source
   local is_build_from_source=false
   local version="$PACKAGE_GCC_DEFAULT_VERSION"
@@ -115,10 +117,19 @@ core() {
 
   while [ "$1" != "" ]; do
     case $1 in
-      -h | --help ) help; exit 0 ;;
-      -b | --build-from-source ) is_build_from_source=true ;;
-      -v | --version ) version=$2; shift ;;
-      * ) echo "Error: Unkown parameter: $1"; exit 1 ;;
+    -h | --help)
+      help
+      exit 0
+      ;;
+    -b | --build-from-source) is_build_from_source=true ;;
+    -v | --version)
+      version=$2
+      shift
+      ;;
+    *)
+      echo "Error: Unkown parameter: $1"
+      exit 1
+      ;;
     esac
     shift
   done
@@ -130,7 +141,6 @@ core() {
   if [ -n "$GCC_VERSION" ]; then
     version="$GCC_VERSION"
   fi
-
 
   if [ "$is_build_from_source" = "true" ]; then
     log::info "Building from source"
