fix: logs better when build failed

diff --git a/install b/install
--- a/install
+++ b/install
@@ -62,6 +62,11 @@ build_from_source() {
   log::info "[gcc::build_from_source] download gcc $version source ..."
   log::info "[gcc::build_from_source] url: $url"
   wget -c $url -O $filepath
+  if [ "$?" != "0" ]; then
+    log::error "[gcc::build_from_source] failed to download gcc $version source code."
+    return 1
+  fi
+
   tar -xzf $filepath -C $build_dir
 
   mv $src_dir_tmp $src_dir
@@ -78,10 +83,19 @@ build_from_source() {
 
   log::info "[gcc::build_from_source] build ..."
   # make -j$(nproc) 
-  make
+  make -j4
+  if [ "$?" != "0" ]; then
+    log::error "[gcc::build_from_source] failed to build gcc $version."
+    return 1
+  fi
 
   log::info "[gcc::build_from_source] install ..."
   make install
+  if [ "$?" != "0" ]; then
+    log::error "[gcc::build_from_source] failed to install gcc $version."
+    return 1
+  fi
+
 
   log::info "[gcc::build_from_source] backup gcc ..."
   if [ ! -f "/usr/bin/gcc_bak" ]; then
