chore: use curl instead of wget

diff --git a/install b/install
--- a/install
+++ b/install
@@ -1,7 +1,7 @@
 #!/bin/bash
 
 # OS:
-#   RedHat 7.9.2009(Core 3.10.0-1160.45.1.el7.x86_64 x86_64) 
+#   RedHat 7.9.2009(Core 3.10.0-1160.45.1.el7.x86_64 x86_64)
 #   CentOS 7
 #
 # Reference:
@@ -32,10 +32,10 @@ build_from_source() {
 
   log::info "[gcc::build_from_source] started ..."
 
-   which bzip2 >> /dev/null 2>&1
-   if [ "$?" != "0" ]; then
-     pm install -y bzip2
-   fi
+  which bzip2 >>/dev/null 2>&1
+  if [ "$?" != "0" ]; then
+    pm install -y bzip2
+  fi
 
   local build_dir=$(os::tmp)/build/zmicro_package_gcc
   mkdir -p $build_dir
@@ -61,7 +61,8 @@ build_from_source() {
 
   log::info "[gcc::build_from_source] download gcc $version source ..."
   log::info "[gcc::build_from_source] url: $url"
-  wget -c $url -O $filepath
+  # wget -c $url -O $filepath
+  os::download $filepath $url
   if [ "$?" != "0" ]; then
     log::error "[gcc::build_from_source] failed to download gcc $version source code."
     return 1
@@ -90,7 +91,7 @@ build_from_source() {
   fi
 
   log::info "[gcc::build_from_source] build ..."
-  # make -j$(nproc) 
+  # make -j$(nproc)
   make -j4
   if [ "$?" != "0" ]; then
     log::error "[gcc::build_from_source] failed to build gcc $version."
@@ -103,7 +104,6 @@ build_from_source() {
     log::error "[gcc::build_from_source] failed to install gcc $version."
     return 1
   fi
-
 
   log::info "[gcc::build_from_source] backup gcc ..."
   if [ ! -f "/usr/bin/gcc_bak" ]; then
@@ -138,7 +138,7 @@ core() {
     help
     exit 0
   fi
-  
+
   # only works when is build from source
   local is_build_from_source=false
   local version="$PACKAGE_GCC_DEFAULT_VERSION"
@@ -146,10 +146,19 @@ core() {
 
   while [ "$1" != "" ]; do
     case $1 in
-      -h | --help ) help; exit 0 ;;
-      -b | --build-from-source ) is_build_from_source=true ;;
-      -v | --version ) version=$2; shift ;;
-      * ) echo "Error: Unkown parameter: $1"; exit 1 ;;
+    -h | --help)
+      help
+      exit 0
+      ;;
+    -b | --build-from-source) is_build_from_source=true ;;
+    -v | --version)
+      version=$2
+      shift
+      ;;
+    *)
+      echo "Error: Unkown parameter: $1"
+      exit 1
+      ;;
     esac
     shift
   done
@@ -161,7 +170,6 @@ core() {
   if [ -n "$GCC_VERSION" ]; then
     version="$GCC_VERSION"
   fi
-
 
   if [ "$is_build_from_source" = "true" ]; then
     log::info "Building from source"
