chore: fix install not load config

diff --git a/install b/install
--- a/install
+++ b/install
@@ -94,17 +94,18 @@ core() {
   
   # only works when is build from source
   local is_build_from_source=false
-  local version="${PACKAGE_GCC_DEFAULT_VERSION}"
+  # local version="${PACKAGE_GCC_DEFAULT_VERSION}"
+  local version="12.1.0"
 
-  while [ "$1" != "" ]; do
-    case $1 in
-      -h | --help ) help; exit 0 ;;
-      -b | --build-from-source ) is_build_from_source=true ;;
-      -v | --version ) version=$2; shift ;;
-      * ) echo "Error: Unkown parameter: $1"; exit 1 ;;
-    esac
-    shift
-  done
+  # while [ "$1" != "" ]; do
+  #   case $1 in
+  #     -h | --help ) help; exit 0 ;;
+  #     -b | --build-from-source ) is_build_from_source=true ;;
+  #     -v | --version ) version=$2; shift ;;
+  #     * ) echo "Error: Unkown parameter: $1"; exit 1 ;;
+  #   esac
+  #   shift
+  # done
 
   if [ -n "$BUILD_FROM_SOURCE" ]; then
     is_build_from_source=true
